name: flutter_chat_gpt
description: "The best Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  desktop_window: ^0.4.0
  dio: ^5.4.1
  equatable: ^2.0.5
  feedback_sentry: ^3.0.0
  feedback: ^3.0.0
  flutter_animate: ^4.5.0
  flutter_hooks: ^0.20.5
  flutter_native_splash: ^2.3.10
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^13.0.1
  hooks_riverpod: ^2.4.10
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  isar_flutter_libs: ^3.1.0+1
  isar: ^3.1.0+1
  overlay_support: ^2.1.0
  path_provider: ^2.1.2
  rive: ^0.12.4
  sentry_flutter: ^7.17.0
  sized_context: ^1.0.0+4
  statsfl: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  freezed: ^2.2.0
  icons_launcher: ^2.1.3
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1



icons_launcher:
  image_path: "assets/images/logo_app.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
flutter_launcher_icons:



flutter:
  # Enable generation of localized Strings from arb files.
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/rive/

  fonts:

    - family: Golos
      fonts:
        - asset: assets/fonts/GolosText-Regular.ttf
        - asset: assets/fonts/GolosText-Medium.ttf
        - asset: assets/fonts/GolosText-SemiBold.ttf
        - asset: assets/fonts/GolosText-Bold.ttf
        - asset: assets/fonts/GolosText-ExtraBold.ttf
        - asset: assets/fonts/GolosText-Black.ttf

