name: flutter_chat_gpt
description: "The best Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter_animate: ^4.5.0
  flutter_hooks: ^0.20.5
  flutter_native_splash: ^2.3.10
  gap: ^3.0.1
  go_router: ^13.0.1
  hooks_riverpod: ^2.4.10
  intl: ^0.18.0
  isar_flutter_libs: ^3.1.0+1
  isar: ^3.1.0+1
  path_provider: ^2.1.2
  rive: ^0.12.4
  sized_context: ^1.0.0+4
  # ---------------------
  statsfl: ^2.3.0
  feedback: ^3.0.0
  internet_connection_checker: ^1.0.0+1
  desktop_window: ^0.4.0
  freezed_annotation: ^2.4.1
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  freezed: ^2.2.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8

flutter:
  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/rive/_common/

  fonts:

    - family: Golos
      fonts:
        - asset: assets/fonts/GolosText-Regular.ttf
        - asset: assets/fonts/GolosText-Medium.ttf
        - asset: assets/fonts/GolosText-SemiBold.ttf
        - asset: assets/fonts/GolosText-Bold.ttf
        - asset: assets/fonts/GolosText-ExtraBold.ttf
        - asset: assets/fonts/GolosText-Black.ttf

